/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

extern void cptr_dummy_func(int x ) ;
int exempleTest(int x ) 
{ 
  int z ;
  int cptr_exempleTest_1  = 0;
  int cptr_exempleTest_2  = 0;

  {
  /* reachable */
  if (x == 0) {
    cptr_exempleTest_1 ++;
    z = 42;
  } else {
    cptr_exempleTest_2 ++;
    z = 54;
  }
  {int cptr_dummy=0;/* UNREACHABLE */
                    while(cptr_dummy>0){cptr_dummy--;}}
#pragma RETURN_BLOCK("exempleTest")
  cptr_dummy_func(cptr_exempleTest_1);
  cptr_dummy_func(cptr_exempleTest_2);
  return (z);
}
}
int main(void) 
{ 
  int y ;
  int tmp ;
  int cptr_main_1  = 0;

  {
  cptr_main_1 ++;
  y = 25;
  tmp = exempleTest(y);
  {int cptr_dummy=0;/* UNREACHABLE */
                    while(cptr_dummy>0){cptr_dummy--;}}
#pragma RETURN_BLOCK("main")
  /* invariant:
  -54+z = 0
  */
  cptr_dummy_func(cptr_main_1);
  return (tmp);
}
}
