/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

int exempleTest(int x ) 
{ 
  int z ;

  {
  if (x == 0) {
/* cptr_exempleTest_1 11 */ ;
    z = 42;
  } else {
/* cptr_exempleTest_2 14 */ ;
    z = 54;
  }
  return (z);
}
}
int main(void) 
{ 
  int y ;
  int tmp ;

  {
/* cptr_main_1 26 */ ;
  y = 25;
  tmp = exempleTest(y);
  return (tmp);
}
}
