/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

extern void cptr_dummy_func(int x ) ;
int main(void) 
{ 
  int y ;
  int x ;
  int cptr_main_1  = 0;
  int cptr_main_2  = 0;
  int cptr_main_3  = 0;
  int cptr_main_4  = 0;

  {
  /* reachable */
  cptr_main_1 ++;
  y = 25;
  x = 0;
  while (x < 10) {
    /* invariant:
    -x+cptr_main_4 = 0
    -x+cptr_main_2 = 0
    cptr_main_3 = 0
    -25+2*x+y = 0
    9-x >= 0
    x >= 0
    */
    cptr_main_2 ++;
    y -= 2;
    if (y % 2 == 0) {
      cptr_main_3 ++;
      y ++;
    }
    cptr_main_4 ++;
    x ++;
  }
  {int cptr_dummy=0;/* UNREACHABLE */
                    while(cptr_dummy>0){cptr_dummy--;}}
#pragma RETURN_BLOCK("main")
  /* invariant:
  -10+cptr_main_4 = 0
  cptr_main_3 = 0
  -10+cptr_main_2 = 0
  -5+y = 0
  */
  cptr_dummy_func(cptr_main_1);
  cptr_dummy_func(cptr_main_2);
  cptr_dummy_func(cptr_main_3);
  cptr_dummy_func(cptr_main_4);
  return (y);
}
}
