/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

int main(void) 
{ 
  int y ;
  int x ;

  {
/* cptr_main_1 11 */ ;
  y = 25;
  x = 0;
  while (x < 10) {
/* cptr_main_2 15 */ ;
    y -= 2;
    if (y % 2 == 0) {
/* cptr_main_3 18 */ ;
      y ++;
    }
/* cptr_main_4 21 */ ;
    x ++;
  }
  return (y);
}
}
