/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

extern void cptr_dummy_func(int x ) ;
int main(void) 
{ 
  int x ;
  int y ;
  int i ;
  int cptr_main_1  = 0;
  int cptr_main_2  = 0;
  int cptr_main_3  = 0;

  {
  /* reachable */
  cptr_main_1 ++;
  x = 0;
  y = 0;
  i = 100;
  while (i > 0) {
    /* invariant:
    y = 0
    cptr_main_3 = 0
    cptr_main_2 = 0
    -100+i = 0
    */
    cptr_main_2 ++;
    x = 12 + y;
    y = 1 + x;
    if (x < 1000) {
      break;
    }
    cptr_main_3 ++;
    i --;
  }
  {int cptr_dummy=0;/* UNREACHABLE */
                    while(cptr_dummy>0){cptr_dummy--;}}
#pragma RETURN_BLOCK("main")
  /* invariant:
  -12+x = 0
  cptr_main_3 = 0
  -1+cptr_main_2 = 0
  */
  cptr_dummy_func(cptr_main_1);
  cptr_dummy_func(cptr_main_2);
  cptr_dummy_func(cptr_main_3);
  return (x);
}
}
