/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

int main(void) 
{ 
  int x ;
  int y ;
  int i ;

  {
/* cptr_main_1 12 */ ;
  x = 0;
  y = 0;
  i = 100;
  while (i > 0) {
/* cptr_main_2 17 */ ;
    x = 12 + y;
    y = 1 + x;
    if (x < 1000) {
      break;
    }
/* cptr_main_3 23 */ ;
    i --;
  }
  return (x);
}
}
