/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

extern void cptr_dummy_func(int x ) ;
int fun2(int i ) ;
int fun1(int i ) 
{ 
  int j ;
  int __retres3 ;
  int i4 ;
  int j5 ;
  int __retres36 ;
  int i47 ;
  int i58 ;
  int cptr_fun1_1  = 0;
  int cptr_fun1_2  = 0;
  int cptr_fun1_3  = 0;
  int cptr_fun1_4  = 0;

  {
  cptr_fun1_1 ++;
  j = 0;
  while (j < 10) {
    cptr_fun1_2 ++;
    i -= 3;
    j ++;
  }
  {
  i4 = i;
  {
  j5 = 0;
  while (j5 < 10) {
    cptr_fun1_3 ++;
    i4 += j5;
    j5 ++;
  }
  if (i4 < 56) {
    {
    i47 = i4;
    {
    i47 = 10;
    goto Lret_fun3;
    }
    Lret_fun3: /* CIL Label */ ;
    }
  } else {
    {
    i58 = i4;
    {
    i58 = 37;
    goto Lret_fun4;
    }
    Lret_fun4: /* CIL Label */ ;
    }
  }
  cptr_fun1_4 ++;
  __retres36 = 0;
  goto Lret_fun2;
  }
  Lret_fun2: /* CIL Label */ ;
  }
  __retres3 = 0;
  {int cptr_dummy=0;while(cptr_dummy>0){cptr_dummy--;}}
#pragma RETURN_BLOCK("fun1")
  cptr_dummy_func(cptr_fun1_1);
  cptr_dummy_func(cptr_fun1_2);
  cptr_dummy_func(cptr_fun1_3);
  cptr_dummy_func(cptr_fun1_4);
  return (__retres3);
}
}
int fun3(int i ) ;
int fun4(int i ) ;
int fun2(int i ) 
{ 
  int j ;
  int __retres3 ;
  int i4 ;
  int i5 ;
  int cptr_fun2_1  = 0;
  int cptr_fun2_2  = 0;
  int cptr_fun2_3  = 0;

  {
  cptr_fun2_1 ++;
  j = 0;
  while (j < 10) {
    cptr_fun2_2 ++;
    i += j;
    j ++;
  }
  if (i < 56) {
    {
    i4 = i;
    {
    i4 = 10;
    goto Lret_fun3;
    }
    Lret_fun3: /* CIL Label */ ;
    }
  } else {
    {
    i5 = i;
    {
    i5 = 37;
    goto Lret_fun4;
    }
    Lret_fun4: /* CIL Label */ ;
    }
  }
  cptr_fun2_3 ++;
  __retres3 = 0;
  {int cptr_dummy=0;while(cptr_dummy>0){cptr_dummy--;}}
#pragma RETURN_BLOCK("fun2")
  cptr_dummy_func(cptr_fun2_1);
  cptr_dummy_func(cptr_fun2_2);
  cptr_dummy_func(cptr_fun2_3);
  return (__retres3);
}
}
int fun3(int i ) 
{ 
  int cptr_fun3_1  = 0;

  {
  cptr_fun3_1 ++;
  i = 10;
  {int cptr_dummy=0;while(cptr_dummy>0){cptr_dummy--;}}
#pragma RETURN_BLOCK("fun3")
  cptr_dummy_func(cptr_fun3_1);
  return (i);
}
}
int fun4(int i ) 
{ 
  int cptr_fun4_1  = 0;

  {
  cptr_fun4_1 ++;
  i = 37;
  {int cptr_dummy=0;while(cptr_dummy>0){cptr_dummy--;}}
#pragma RETURN_BLOCK("fun4")
  cptr_dummy_func(cptr_fun4_1);
  return (i);
}
}
int main(void) 
{ 
  int var ;
  int i2 ;
  int j3 ;
  int __retres34 ;
  int i45 ;
  int j56 ;
  int __retres367 ;
  int i478 ;
  int i589 ;
  int cptr_main_1  = 0;
  int cptr_main_2  = 0;
  int cptr_main_3  = 0;

  {
  {
  var = 156;
  i2 = var;
  {
  j3 = 0;
  while (j3 < 10) {
    cptr_main_1 ++;
    i2 -= 3;
    j3 ++;
  }
  {
  i45 = i2;
  {
  j56 = 0;
  while (j56 < 10) {
    cptr_main_2 ++;
    i45 += j56;
    j56 ++;
  }
  if (i45 < 56) {
    {
    i478 = i45;
    {
    i478 = 10;
    goto Lret_fun3;
    }
    Lret_fun3: /* CIL Label */ ;
    }
  } else {
    {
    i589 = i45;
    {
    i589 = 37;
    goto Lret_fun4;
    }
    Lret_fun4: /* CIL Label */ ;
    }
  }
  cptr_main_3 ++;
  __retres367 = 0;
  goto Lret_fun2;
  }
  Lret_fun2: /* CIL Label */ ;
  }
  __retres34 = 0;
  goto Lret_fun1;
  }
  Lret_fun1: /* CIL Label */ ;
  }
  {int cptr_dummy=0;while(cptr_dummy>0){cptr_dummy--;}}
#pragma RETURN_BLOCK("main")
  cptr_dummy_func(cptr_main_1);
  cptr_dummy_func(cptr_main_2);
  cptr_dummy_func(cptr_main_3);
  return (var);
}
}
