/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

extern void cptr_dummy_func(int x ) ;
int main(void) 
{ 
  int y ;
  int z ;
  int x ;
  int x___0 ;
  int cptr_main_1  = 0;
  int cptr_main_2  = 0;
  int cptr_main_3  = 0;
  int cptr_main_4  = 0;
  int cptr_main_5  = 0;
  int cptr_main_6  = 0;
  int cptr_main_7  = 0;

  {
  /* reachable */
  cptr_main_1 ++;
  y = 20;
  z = 3;
  x = 0;
  while (x < 20) {
    /* invariant:
    20-y-x+2*cptr_main_2 = 0
    -x+cptr_main_4 = 0
    -20+y-x+2*cptr_main_3 = 0
    380-19*y-x >= 0
    y-x >= 0
    -20+y+x >= 0
    */
    if (y == x) {
      cptr_main_2 ++;
      y ++;
    } else {
      cptr_main_3 ++;
      y --;
    }
    cptr_main_4 ++;
    x ++;
  }
  if (y == 0) {
    cptr_main_5 ++;
    x___0 = 0;
    /* UNREACHABLE */
    while (x___0 < 100) {
      cptr_main_6 ++;
      y = z + y;
      x___0 ++;
    }
  } else {
    cptr_main_7 ++;
    y = 1;
  }
  {int cptr_dummy=0;/* UNREACHABLE */
                    while(cptr_dummy>0){cptr_dummy--;}}
#pragma RETURN_BLOCK("main")
  /* invariant:
  -1+cptr_main_7 = 0
  cptr_main_6 = 0
  cptr_main_5 = 0
  -20+cptr_main_4 = 0
  -10+cptr_main_3 = 0
  -10+cptr_main_2 = 0
  -1+y = 0
  */
  cptr_dummy_func(cptr_main_1);
  cptr_dummy_func(cptr_main_2);
  cptr_dummy_func(cptr_main_3);
  cptr_dummy_func(cptr_main_4);
  cptr_dummy_func(cptr_main_5);
  cptr_dummy_func(cptr_main_6);
  cptr_dummy_func(cptr_main_7);
  return (y);
}
}
