/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

extern void cptr_dummy_func(int x ) ;
int x  =    7;
int y  =    10;
int z  =    15;
int main(void) 
{ 
  int t[10] ;
  int i ;
  int cptr_main_1  = 0;
  int cptr_main_2  = 0;
  int cptr_main_3  = 0;
  int cptr_main_4  = 0;
  int cptr_main_5  = 0;
  int cptr_main_6  = 0;
  int cptr_main_7  = 0;
  int cptr_main_8  = 0;

  {
  /* reachable */
  cptr_main_1 ++;
  i = 0;
  /* invariant:
  -cptr_main_2+i = 0
  9-cptr_main_2 >= 0
  cptr_main_2 >= 0
  */
  while (i < 10) {
    cptr_main_2 ++;
    t[i] = i - x;
    i ++;
  }
  i = 0;
  while (i < 10) {
    /* invariant:
    10-y.0+cptr_main_3 = 0
    -i+cptr_main_6 = 0
    -10+cptr_main_2 = 0
    -3+y.0-x.0+cptr_main_4 = 0
    -15+z.0+cptr_main_5 = 0
    31-z.0-y.0 >= 0
    25-z.0-y.0+i >= 0
    29-y.0-x.0+i >= 0
    17-y.0-x.0+3*i >= 0
    16-y.0 >= 0
    10-y.0+i >= 0
    9-i >= 0
    i >= 0
    -8+z.0-x.0+3*i >= 0
    -15+z.0+i >= 0
    3+2*z.0-2*x.0+2*i >= 0
    -9+2*z.0-2*x.0+4*i >= 0
    -16+2*z.0-x.0+2*i >= 0
    -41+16*z.0-11*x.0+11*i >= 0
    */
    if (i <= 5) {
      cptr_main_3 ++;
      y ++;
      x ++;
    }
    if (t[i] >= 0) {
      cptr_main_4 ++;
      x ++;
    }
    if (x < 15) {
      cptr_main_5 ++;
      z --;
    }
    cptr_main_6 ++;
    i ++;
  }
  if (z <= 5) {
    cptr_main_7 ++;
    x = 0;
  }
  if (y < 20) {
    cptr_main_8 ++;
    z = 0;
  }
  {int cptr_dummy=0;/* UNREACHABLE */
                    while(cptr_dummy>0){cptr_dummy--;}}
#pragma RETURN_BLOCK("main")
  /* invariant:
  -1+cptr_main_8 = 0
  -10+cptr_main_6 = 0
  -10+cptr_main_2 = 0
  309-11*cptr_main_8-16*cptr_main_5-149*cptr_main_7 >= 0
  53-2*cptr_main_8-2*cptr_main_5-33*cptr_main_7 >= 0
  29-cptr_main_8-cptr_main_3-23*cptr_main_7 >= 0
  6-cptr_main_3 >= 0
  6-cptr_main_3+cptr_main_5-10*cptr_main_7 >= 0
  9-cptr_main_5+cptr_main_7 >= 0
  1-cptr_main_7 >= 0
  cptr_main_7 >= 0
  -7+cptr_main_8-cptr_main_3-cptr_main_4+14*cptr_main_7 >= 0
  */
  cptr_dummy_func(cptr_main_1);
  cptr_dummy_func(cptr_main_2);
  cptr_dummy_func(cptr_main_3);
  cptr_dummy_func(cptr_main_4);
  cptr_dummy_func(cptr_main_5);
  cptr_dummy_func(cptr_main_6);
  cptr_dummy_func(cptr_main_7);
  cptr_dummy_func(cptr_main_8);
  return (x);
}
}
