/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

int x  =    7;
int y  =    10;
int z  =    15;
int main(void) 
{ 
  int t[10] ;
  int i ;

  {
/* cptr_main_1 14 */ ;
  i = 0;
  while (i < 10) {
/* cptr_main_2 17 */ ;
    t[i] = i - x;
    i ++;
  }
  i = 0;
  while (i < 10) {
    if (i <= 5) {
/* cptr_main_3 24 */ ;
      y ++;
      x ++;
    }
    if (t[i] >= 0) {
/* cptr_main_4 29 */ ;
      x ++;
    }
    if (x < 15) {
/* cptr_main_5 33 */ ;
      z --;
    }
/* cptr_main_6 36 */ ;
    i ++;
  }
  if (z <= 5) {
/* cptr_main_7 40 */ ;
    x = 0;
  }
  if (y < 20) {
/* cptr_main_8 44 */ ;
    z = 0;
  }
  return (x);
}
}
