/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

extern void cptr_dummy_func(int x ) ;
int main(void) 
{ 
  int t[10] ;
  int i ;
  int x ;
  int y ;
  int z ;
  int cptr_main_1  = 0;
  int cptr_main_2  = 0;
  int cptr_main_3  = 0;
  int cptr_main_4  = 0;
  int cptr_main_5  = 0;
  int cptr_main_6  = 0;
  int cptr_main_7  = 0;
  int cptr_main_8  = 0;

  {
  cptr_main_1 ++;
  x = 7;
  y = 10;
  z = 15;
  i = 0;
  while (i < 10) {
    cptr_main_2 ++;
    t[i] = i - x;
    i ++;
  }
  i = 0;
  while (i < 10) {
    if (i <= 5) {
      cptr_main_3 ++;
      y ++;
      x ++;
    }
    if (t[i] >= 0) {
      cptr_main_4 ++;
      x ++;
    }
    if (x < 15) {
      cptr_main_5 ++;
      z --;
    }
    if (y > 5) {
      break;
    }
    cptr_main_6 ++;
    i ++;
  }
  if (z <= 5) {
    cptr_main_7 ++;
    x = 0;
  }
  if (y < 20) {
    cptr_main_8 ++;
    z = 0;
  }
  {int cptr_dummy=0;while(cptr_dummy>0){cptr_dummy--;}}
#pragma RETURN_BLOCK("main")
  cptr_dummy_func(cptr_main_1);
  cptr_dummy_func(cptr_main_2);
  cptr_dummy_func(cptr_main_3);
  cptr_dummy_func(cptr_main_4);
  cptr_dummy_func(cptr_main_5);
  cptr_dummy_func(cptr_main_6);
  cptr_dummy_func(cptr_main_7);
  cptr_dummy_func(cptr_main_8);
  return (x);
}
}
